stages:
  - test

default:
  tags:
    - k8s
    - amd64
  services:
    - name: postgres:18
    - name: eclipse-mosquitto:2
      alias: mosquitto
      entrypoint: ["sh", "-c"]
      command:
        - |
          printf 'listener 1883\nallow_anonymous true\n' > /tmp/mosquitto.conf &&
          /usr/sbin/mosquitto -c /tmp/mosquitto.conf
    - name: open62541/open62541:latest
      alias: opcua
  before_script:
    - |
        curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
        -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
        -d "{\"state\": \"pending\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
    - set +e

variables:
  REPO_NAME: module-jni
  POSTGRES_PASSWORD: omq
  QORE_DB_CONNSTR: pgsql:postgres/omq@postgres%postgres
  MQTT_CONNECTION: "mqtttcp://mosquitto:1883"
  OPCUA_CONNECTION: "opc.tcp://opcua:4840"
  TZ: Europe/Prague
  PGTZ: Europe/Prague

test-ubuntu:
  stage: test
  image: $CI_REGISTRY/infrastructure/qore-test-base/qore-test-base:develop
  script:
    - |
        if test/docker_test/test-ubuntu.sh; then
          curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"success\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 0
        else
          curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"failure\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 1
        fi

test-alpine:
  stage: test
  image: $CI_REGISTRY/infrastructure/qore-test-base/qore-test-base:develop-alpine
  script:
    - |
        if test/docker_test/test-alpine.sh; then
          curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"success\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 0
        else
          curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"failure\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 1
        fi
