#!/bin/sh
# Copyright (C) 2026 David Nichols
# SPDX-License-Identifier: MIT
set -eu
unset QORE_MODULE_DIR QORE_MODULE_DIR_ONLY QORE_INCLUDE_DIR LD_LIBRARY_PATH LD_PRELOAD KOTLIN_HOME
unset CLASSPATH QORE_CLASSPATH QORE_JNI_CLASSPATH JAVA_TOOL_OPTIONS JDK_JAVA_OPTIONS _JAVA_OPTIONS
export QORE_MODULE_DIR=$(/usr/bin/qore --module-path)
export QORE_MODULE_DIR_ONLY=1
export QORE_JNI_CLASSPATH=/usr/share/qore/java/qore-jni.jar:/usr/share/qore/java/qore-jni-compiler.jar
cp -a test "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
qkotlinc -q -jvm-target 21 -d test/kotlin-test.jar test/KotlinQoreApiTest.kt test/KotlinTestClass.kt
timeout 300 /usr/bin/qore -l jni test/kotlin.qtest -v
